# Generated by Django 3.0.7 on 2020-06-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClass',
            fields=[
                ('course_number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank='True', default='', max_length=50, null='False')),
                ('instructor_name', models.CharField(blank='True', default='', max_length=50, null='False')),
                ('duration', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
    ]
